services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: supermarket-oracle
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: 123456
      APP_USER: appuser
      APP_USER_PASSWORD: apppass
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./database:/workspace-database:ro
      - ./database/init:/container-entrypoint-initdb.d:ro

volumes:
  oracle-data:
