services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: supermarket-oracle
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: Admin123
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./database:/container-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  oracle-data: