package view;

import business.sql.rbac.AccountSql;
import business.sql.rbac.RoleSql;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author nguye
 */
public class CreateAccountPanel extends javax.swing.JPanel {
    
    private final Color bgLight = new Color(244, 246, 250);
    private final Color cardWhite = Color.WHITE;
    private final Color primaryBlue = new Color(67, 97, 238);
    private final Color textDark = new Color(43, 54, 116);
    private final Color textGray = new Color(163, 174, 208);
    private final Color borderGray = new Color(230, 235, 241);

    private JTextField txtFullName, txtEmail, txtPhone, txtUsername;
    private JComboBox<String> cbRole;

    /**
     * Creates new form CreateAccountPanel
     */
    public CreateAccountPanel() {
        initComponents();
        setLayout(new BorderLayout(0, 20));
        setBackground(bgLight);
        setBorder(new EmptyBorder(30, 40, 30, 40));
        initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        
    private void initUI() {
        // --- 1. HEADER TỔNG ---
        JPanel headerPanel = new JPanel(new GridLayout(2, 1));
        headerPanel.setBackground(bgLight);
        JLabel lblTitle = new JLabel("Tạo Tài Khoản Mới");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 26));
        lblTitle.setForeground(textDark);
        JLabel lblSub = new JLabel("Thêm nhân viên vào hệ thống và cấp quyền trực tiếp (Mật khẩu mặc định: 1234)");
        lblSub.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblSub.setForeground(textGray);
        headerPanel.add(lblTitle);
        headerPanel.add(lblSub);
        add(headerPanel, BorderLayout.NORTH);

        // --- 2. CARD CHỨA FORM CHÍNH (ĐÃ CĂN GIỮA) ---
        // Dùng GridBagLayout ở đây sẽ tự động đẩy mọi component bên trong ra chính giữa
        JPanel centerContainer = new JPanel(new GridBagLayout());
        centerContainer.setBackground(bgLight);

        RoundedPanel formCard = new RoundedPanel(20, cardWhite);
        formCard.setLayout(new GridBagLayout());
        formCard.setBorder(new EmptyBorder(40, 50, 40, 50)); 

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.weightx = 1.0;

        // --- KHU VỰC AVATAR ---
        JPanel avatarPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(240, 242, 248)); 
                g2.fillOval(0, 0, 100, 100);
                
                g2.setColor(textGray);
                g2.setFont(new Font("Segoe UI", Font.BOLD, 14));
                FontMetrics fm = g2.getFontMetrics();
                String txt = "+ Tải ảnh";
                g2.drawString(txt, (100 - fm.stringWidth(txt)) / 2, (100 - fm.getHeight()) / 2 + fm.getAscent());
                g2.dispose();
            }
        };
        avatarPanel.setPreferredSize(new Dimension(100, 100));
        avatarPanel.setOpaque(false);
        avatarPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        avatarPanel.setToolTipText("Nhấn để chọn ảnh đại diện (Đang phát triển)");
        
        JPanel avatarContainer = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0));
        avatarContainer.setOpaque(false);
        avatarContainer.add(avatarPanel);
        
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        gbc.insets = new Insets(0, 0, 30, 0);
        formCard.add(avatarContainer, gbc);

        // --- KHU VỰC NHẬP LIỆU ---
        gbc.gridwidth = 1;

        txtFullName = createTextField("Nhập họ và tên");
        txtUsername = createTextField("Tạo tên đăng nhập");
        txtEmail = createTextField("Nhập địa chỉ email");
        txtPhone = createTextField("Nhập số điện thoại");

        List<String> roles = RoleSql.getInstance().getAvailableRoles();
        cbRole = new JComboBox<>(roles.toArray(new String[0]));
        cbRole.setPreferredSize(new Dimension(300, 45));
        cbRole.setBackground(Color.WHITE);
        cbRole.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        cbRole.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(borderGray, 10), new EmptyBorder(5, 10, 5, 10)
        ));

        // Hàng 1
        gbc.gridy = 1; 
        gbc.gridx = 0; gbc.insets = new Insets(0, 0, 8, 20); formCard.add(createLabel("Họ và Tên (*)"), gbc);
        gbc.gridx = 1; gbc.insets = new Insets(0, 0, 8, 0);  formCard.add(createLabel("Tên đăng nhập (*)"), gbc);
        
        gbc.gridy = 2; 
        gbc.gridx = 0; gbc.insets = new Insets(0, 0, 20, 20); formCard.add(txtFullName, gbc);
        gbc.gridx = 1; gbc.insets = new Insets(0, 0, 20, 0);  formCard.add(txtUsername, gbc);

        // Hàng 2
        gbc.gridy = 3; 
        gbc.gridx = 0; gbc.insets = new Insets(0, 0, 8, 20); formCard.add(createLabel("Email (*)"), gbc);
        gbc.gridx = 1; gbc.insets = new Insets(0, 0, 8, 0);  formCard.add(createLabel("Số điện thoại (*)"), gbc);
        
        gbc.gridy = 4; 
        gbc.gridx = 0; gbc.insets = new Insets(0, 0, 20, 20); formCard.add(txtEmail, gbc);
        gbc.gridx = 1; gbc.insets = new Insets(0, 0, 20, 0);  formCard.add(txtPhone, gbc);

        // Hàng 3
        gbc.gridy = 5; 
        gbc.gridx = 0; gbc.gridwidth = 2; gbc.insets = new Insets(0, 0, 8, 0); 
        formCard.add(createLabel("Cấp Quyền (Role) (*)"), gbc);
        
        gbc.gridy = 6; 
        gbc.insets = new Insets(0, 0, 35, 0); 
        formCard.add(cbRole, gbc);

        // --- NÚT SUBMIT ---
        JButton btnCreate = createCustomButton("Tạo Tài Khoản", primaryBlue, Color.WHITE);
        btnCreate.addActionListener(e -> handleCreateAccount());

        JPanel btnContainer = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
        btnContainer.setOpaque(false);
        btnContainer.add(btnCreate);

        gbc.gridy = 7; 
        gbc.insets = new Insets(0, 0, 0, 0);
        formCard.add(btnContainer, gbc);

        centerContainer.add(formCard); // Đưa formCard vào centerContainer (hiện tại dùng GridBagLayout sẽ tự căn giữa)
        add(centerContainer, BorderLayout.CENTER);
    }

    private JLabel createLabel(String text) {
        JLabel lbl = new JLabel(text);
        lbl.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lbl.setForeground(textDark);
        return lbl;
    }

    private JTextField createTextField(String placeholder) {
        JTextField txt = new JTextField();
        txt.setPreferredSize(new Dimension(320, 45)); 
        txt.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txt.putClientProperty("JTextField.placeholderText", placeholder);
        txt.setBorder(BorderFactory.createCompoundBorder(
                new RoundBorder(borderGray, 10), new EmptyBorder(5, 15, 5, 15)
        ));
        return txt;
    }

    private JButton createCustomButton(String text, Color bg, Color fg) {
        JButton btn = new JButton(text) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(bg);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 10, 10);
                super.paintComponent(g);
                g2.dispose();
            }
        };
        btn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btn.setForeground(fg);
        btn.setPreferredSize(new Dimension(180, 45));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        btn.addMouseListener(new MouseAdapter() {
            @Override public void mouseEntered(MouseEvent e) { btn.setBackground(new Color(50, 75, 200)); }
            @Override public void mouseExited(MouseEvent e) { btn.setBackground(bg); }
        });
        
        return btn;
    }

    private void handleCreateAccount() {
        String name = txtFullName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String user = txtUsername.getText().trim();
        String role = (String) cbRole.getSelectedItem();

        if (name.isEmpty() || email.isEmpty() || phone.isEmpty() || user.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin bắt buộc!", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }

        AccountSql accSql = AccountSql.getInstance();
        boolean success = accSql.createEmployeeAccount(name, email, phone, user, role);

        if (success) {
            JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công!\nMật khẩu đăng nhập mặc định là: 1234", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            txtFullName.setText("");
            txtEmail.setText("");
            txtPhone.setText("");
            txtUsername.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Tạo thất bại! Có thể Username/Email đã tồn tại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    class RoundedPanel extends JPanel {
        private int radius;
        private Color bgColor;

        public RoundedPanel(int radius, Color bgColor) {
            this.radius = radius;
            this.bgColor = bgColor;
            setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(bgColor);
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
            g2.dispose();
            super.paintComponent(g);
        }
    }

    class RoundBorder implements javax.swing.border.Border {
        private Color color;
        private int radius;

        public RoundBorder(Color color, int radius) {
            this.color = color;
            this.radius = radius;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(color);
            g2.setStroke(new BasicStroke(1.2f));
            g2.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
            g2.dispose();
        }
        @Override public Insets getBorderInsets(Component c) { return new Insets(1, 1, 1, 1); }
        @Override public boolean isBorderOpaque() { return false; }
    }
    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
