package view;

import common.events.AppDataChangedEvent;
import common.events.AppEventType;
import common.events.EventBus;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.event.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

public class StoreManagementPanel extends JPanel{
 static final String ACTIVE="Hoạt động",INACTIVE="Tạm ngưng";
 Color bg=new Color(244,246,250),navy=new Color(31,42,68),text=new Color(36,47,74),muted=new Color(111,124,145),line=new Color(226,232,240),primary=new Color(37,99,235),danger=new Color(220,38,38);
 JTable tblStores; DefaultTableModel tableModel; JTextField txtSearch,txtMaSieuThi,txtTenSieuThi,txtDiaChi,txtSoDienThoai; JComboBox<String> cbTrangThai; JButton btnSave,btnClear,btnSoftDelete; JLabel lblTotal,lblActive,lblInactive,lblHint; boolean isEditMode,hasName,hasStatus;
 public StoreManagementPanel(){setLayout(new BorderLayout(0,22));setBackground(bg);setBorder(new EmptyBorder(24,30,24,30));initUI();initEvents();refreshStoreSchemaFlags();loadStoreData("");}

 private void initUI(){add(createHeaderPanel(),BorderLayout.NORTH);JPanel body=new JPanel(new BorderLayout(22,0));body.setOpaque(false);body.add(createTablePanel(),BorderLayout.CENTER);body.add(createFormPanel(),BorderLayout.EAST);add(body,BorderLayout.CENTER);}
 private JPanel createHeaderPanel(){JPanel p=new JPanel(new GridLayout(2,1,0,4));p.setOpaque(false);JLabel t=new JLabel("Quản Lý Chuỗi Siêu Thị");t.setFont(new Font("Segoe UI",1,28));t.setForeground(text);JLabel s=new JLabel("Theo dõi, cập nhật và kiểm soát trạng thái toàn bộ chi nhánh trong hệ thống");s.setFont(new Font("Segoe UI",0,14));s.setForeground(muted);p.add(t);p.add(s);return p;}
 private JPanel createStatsPanel(){JPanel p=new JPanel(new GridLayout(1,3,14,0));p.setOpaque(false);p.setBorder(new EmptyBorder(0,0,18,0));lblTotal=new JLabel("0");lblActive=new JLabel("0");lblInactive=new JLabel("0");p.add(stat("Tổng chi nhánh",lblTotal));p.add(stat("Đang hoạt động",lblActive));p.add(stat("Tạm ngưng",lblInactive));return p;}
 private JPanel stat(String title,JLabel v){JPanel c=card();c.setLayout(new GridLayout(2,1,0,2));JLabel l=new JLabel(title);l.setForeground(muted);l.setFont(new Font("Segoe UI",0,13));v.setFont(new Font("Segoe UI",1,24));v.setForeground(text);c.add(l);c.add(v);return c;}
 private JPanel createTablePanel(){JPanel card=card();card.setLayout(new BorderLayout());card.add(createStatsPanel(),BorderLayout.NORTH);JPanel wrap=new JPanel(new BorderLayout(0,16));wrap.setOpaque(false);JPanel bar=new JPanel(new BorderLayout());bar.setOpaque(false);JLabel title=new JLabel("Danh sách chi nhánh");title.setFont(new Font("Segoe UI",1,18));title.setForeground(text);txtSearch=field("Tìm kiếm chi nhánh...");txtSearch.setPreferredSize(new Dimension(280,40));bar.add(title,BorderLayout.WEST);bar.add(txtSearch,BorderLayout.EAST);tableModel=new DefaultTableModel(new Object[]{"Mã Cửa Hàng","Tên Siêu Thị","Trạng Thái"},0){public boolean isCellEditable(int r,int c){return false;}};tblStores=new JTable(tableModel);setupTableStyle();JScrollPane sp=new JScrollPane(tblStores);sp.setBorder(new LineBorder(line));wrap.add(bar,BorderLayout.NORTH);wrap.add(sp,BorderLayout.CENTER);card.add(wrap,BorderLayout.CENTER);return card;}
 private JPanel createFormPanel(){JPanel c=card();c.setPreferredSize(new Dimension(400,0));c.setLayout(new BorderLayout(0,18));JPanel h=new JPanel(new GridLayout(2,1,0,4));h.setOpaque(false);JLabel t=new JLabel("Thông Tin Siêu Thị");t.setFont(new Font("Segoe UI",1,20));t.setForeground(text);lblHint=new JLabel("Chọn một dòng để cập nhật hoặc nhập mới");lblHint.setForeground(muted);h.add(t);h.add(lblHint);JPanel f=new JPanel(new GridBagLayout());f.setOpaque(false);GridBagConstraints g=new GridBagConstraints();g.gridx=0;g.fill=GridBagConstraints.HORIZONTAL;g.weightx=1;addField(f,g,0,"Mã siêu thị",txtMaSieuThi=field("VD: ST001"));addField(f,g,2,"Tên siêu thị",txtTenSieuThi=field("Nhập tên chi nhánh..."));addField(f,g,4,"Số điện thoại",txtSoDienThoai=field("Nhập số điện thoại..."));addField(f,g,6,"Địa chỉ",txtDiaChi=field("Nhập địa chỉ chi nhánh..."));g.gridy=8;g.insets=new Insets(0,0,6,0);f.add(label("Trạng thái"),g);cbTrangThai=new JComboBox<>(new String[]{ACTIVE,INACTIVE});cbTrangThai.setPreferredSize(new Dimension(0,42));g.gridy=9;g.insets=new Insets(0,0,18,0);f.add(cbTrangThai,g);JPanel a=new JPanel(new GridLayout(3,1,0,10));a.setOpaque(false);btnSave=button("Lưu Thông Tin",primary,Color.WHITE);btnClear=button("Làm Mới",new Color(235,238,244),text);btnSoftDelete=button("Xóa mềm",danger,Color.WHITE);a.add(btnSave);a.add(btnClear);a.add(btnSoftDelete);c.add(h,BorderLayout.NORTH);c.add(f,BorderLayout.CENTER);c.add(a,BorderLayout.SOUTH);return c;}
 private void addField(JPanel p,GridBagConstraints g,int y,String l,JTextField f){g.gridy=y;g.insets=new Insets(0,0,6,0);p.add(label(l),g);g.gridy=y+1;g.insets=new Insets(0,0,14,0);p.add(f,g);}
 private void setupTableStyle(){tblStores.setRowHeight(42);tblStores.setFont(new Font("Segoe UI",0,14));tblStores.setSelectionBackground(new Color(219,234,254));tblStores.setAutoCreateRowSorter(true);tblStores.getTableHeader().setPreferredSize(new Dimension(0,46));tblStores.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){public Component getTableCellRendererComponent(JTable t,Object v,boolean s,boolean f,int r,int c){JLabel l=(JLabel)super.getTableCellRendererComponent(t,v,s,f,r,c);l.setBackground(navy);l.setForeground(Color.WHITE);l.setFont(new Font("Segoe UI",1,13));return l;}});}
 private void initEvents(){btnClear.addActionListener(e->clearForm());btnSave.addActionListener(e->saveStore());btnSoftDelete.addActionListener(e->softDeleteStore());txtSearch.getDocument().addDocumentListener(new DocumentListener(){public void insertUpdate(DocumentEvent e){loadStoreData(txtSearch.getText().trim());}public void removeUpdate(DocumentEvent e){loadStoreData(txtSearch.getText().trim());}public void changedUpdate(DocumentEvent e){loadStoreData(txtSearch.getText().trim());}});tblStores.addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){int r=tblStores.getSelectedRow();if(r>=0){int m=tblStores.convertRowIndexToModel(r);isEditMode=true;String id=String.valueOf(tableModel.getValueAt(m,0));txtMaSieuThi.setText(id);txtMaSieuThi.setEnabled(false);lblHint.setText("Đang cập nhật chi nhánh "+id);loadStoreDetailsToForm(id);}}});}
 private void clearForm(){isEditMode=false;txtMaSieuThi.setEnabled(true);txtMaSieuThi.setText("");txtTenSieuThi.setText("");txtDiaChi.setText("");txtSoDienThoai.setText("");cbTrangThai.setSelectedItem(ACTIVE);tblStores.clearSelection();lblHint.setText("Chọn một dòng để cập nhật hoặc nhập mới");}

 private void loadStoreData(String kw){tableModel.setRowCount(0);refreshStoreSchemaFlags();String ne=nameExpr(),se=statusExpr(),sql="SELECT store_id,"+ne+" display_name,"+se+" display_status,NVL(is_deleted,0) deleted_flag FROM STORES WHERE LOWER(store_id) LIKE LOWER(?) OR LOWER("+ne+") LIKE LOWER(?) OR LOWER(NVL(address,'')) LIKE LOWER(?) OR LOWER(NVL(phone_number,'')) LIKE LOWER(?) ORDER BY store_id";int total=0,active=0,inactive=0;try(Connection con=common.db.DatabaseConnection.getConnection();PreparedStatement ps=con.prepareStatement(sql)){String k="%"+(kw==null?"":kw)+"%";for(int i=1;i<=4;i++)ps.setString(i,k);try(ResultSet rs=ps.executeQuery()){while(rs.next()){String id=safe(rs.getString("store_id")),name=safe(rs.getString("display_name")),st=normalizeStatus(rs.getString("display_status"),rs.getInt("deleted_flag"));total++;if(INACTIVE.equals(st))inactive++;else active++;tableModel.addRow(new Object[]{id,name.isEmpty()?id:name,st});}}}catch(Exception e){System.err.println("Lỗi tải danh sách chi nhánh: "+e.getMessage());}updateStats(total,active,inactive);}
 private void loadStoreDetailsToForm(String id){refreshStoreSchemaFlags();String sql="SELECT address,phone_number,NVL(is_deleted,0) deleted_flag,"+nameExpr()+" display_name,"+statusExpr()+" display_status FROM STORES WHERE store_id=?";try(Connection con=common.db.DatabaseConnection.getConnection();PreparedStatement ps=con.prepareStatement(sql)){ps.setString(1,id);try(ResultSet rs=ps.executeQuery()){if(rs.next()){String n=safe(rs.getString("display_name"));txtTenSieuThi.setText(n.isEmpty()?id:n);txtDiaChi.setText(safe(rs.getString("address")));txtSoDienThoai.setText(safe(rs.getString("phone_number")));cbTrangThai.setSelectedItem(normalizeStatus(rs.getString("display_status"),rs.getInt("deleted_flag")));}}}catch(Exception e){JOptionPane.showMessageDialog(this,"Không thể tải thông tin chi nhánh: "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);}}
 private void saveStore(){String id=txtMaSieuThi.getText().trim(),name=txtTenSieuThi.getText().trim(),addr=txtDiaChi.getText().trim(),phone=txtSoDienThoai.getText().trim(),st=String.valueOf(cbTrangThai.getSelectedItem());if(id.isEmpty()||name.isEmpty()){JOptionPane.showMessageDialog(this,"Vui lòng nhập mã và tên chi nhánh!","Cảnh báo",JOptionPane.WARNING_MESSAGE);return;}refreshStoreSchemaFlags();try(Connection con=common.db.DatabaseConnection.getConnection()){if(isEditMode)updateStore(con,id,name,addr,phone,st);else insertStore(con,id,name,addr,phone,st);business.service.AuditLogService.logAction(isEditMode?"CẬP NHẬT":"THÊM MỚI","STORES",id,"","Trạng thái: "+st,"Admin cập nhật thông tin chi nhánh");JOptionPane.showMessageDialog(this,"Đã lưu thông tin chi nhánh!","Thành công",JOptionPane.INFORMATION_MESSAGE);clearForm();loadStoreData(txtSearch.getText().trim());EventBus.publish(new AppDataChangedEvent(AppEventType.STORE_INFO,"STORE_UPDATED"));}catch(Exception e){JOptionPane.showMessageDialog(this,"Lỗi khi lưu dữ liệu: "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);}}
 private void insertStore(Connection c,String id,String name,String addr,String phone,String st)throws SQLException{String cols="store_id,address,phone_number,is_deleted",vals="?,?,?,?";if(hasName){cols+=",store_name";vals+=",?";}if(hasStatus){cols+=",status";vals+=",?";}try(PreparedStatement ps=c.prepareStatement("INSERT INTO STORES ("+cols+") VALUES ("+vals+")")){int i=1;ps.setString(i++,id);ps.setString(i++,addr);ps.setString(i++,phone);ps.setInt(i++,flag(st));if(hasName)ps.setString(i++,name);if(hasStatus)ps.setString(i,st);ps.executeUpdate();}}
 private void updateStore(Connection c,String id,String name,String addr,String phone,String st)throws SQLException{StringBuilder sql=new StringBuilder("UPDATE STORES SET address=?,phone_number=?,is_deleted=?");if(hasName)sql.append(",store_name=?");if(hasStatus)sql.append(",status=?");sql.append(" WHERE store_id=?");try(PreparedStatement ps=c.prepareStatement(sql.toString())){int i=1;ps.setString(i++,addr);ps.setString(i++,phone);ps.setInt(i++,flag(st));if(hasName)ps.setString(i++,name);if(hasStatus)ps.setString(i++,st);ps.setString(i,id);ps.executeUpdate();}}
 private void softDeleteStore(){String id=txtMaSieuThi.getText().trim();if(id.isEmpty()||!isEditMode){JOptionPane.showMessageDialog(this,"Vui lòng chọn một chi nhánh để xóa mềm.","Cảnh báo",JOptionPane.WARNING_MESSAGE);return;}if(JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn tạm ngưng chi nhánh "+id+"?","Xác nhận xóa mềm",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)return;refreshStoreSchemaFlags();String sql=hasStatus?"UPDATE STORES SET is_deleted=1,status=? WHERE store_id=?":"UPDATE STORES SET is_deleted=1 WHERE store_id=?";try(Connection con=common.db.DatabaseConnection.getConnection();PreparedStatement ps=con.prepareStatement(sql)){if(hasStatus){ps.setString(1,INACTIVE);ps.setString(2,id);}else ps.setString(1,id);ps.executeUpdate();business.service.AuditLogService.logAction("XÓA MỀM","STORES",id,"","is_deleted=1","Admin tạm ngưng chi nhánh");clearForm();loadStoreData(txtSearch.getText().trim());EventBus.publish(new AppDataChangedEvent(AppEventType.STORE_INFO,"STORE_UPDATED"));}catch(Exception e){JOptionPane.showMessageDialog(this,"Lỗi khi xóa mềm: "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);}}

 private void refreshStoreSchemaFlags(){hasName=hasColumn("STORES","STORE_NAME");hasStatus=hasColumn("STORES","STATUS");}
 private boolean hasColumn(String t,String c){try(Connection con=common.db.DatabaseConnection.getConnection();PreparedStatement ps=con.prepareStatement("SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME=? AND COLUMN_NAME=?")){ps.setString(1,t);ps.setString(2,c);try(ResultSet rs=ps.executeQuery()){return rs.next()&&rs.getInt(1)>0;}}catch(Exception e){return false;}}
 private String nameExpr(){return hasName?"NVL(store_name,NVL(address,store_id))":"NVL(address,store_id)";}
 private String statusExpr(){return hasStatus?"NVL(status,CASE WHEN NVL(is_deleted,0)=1 THEN '"+INACTIVE+"' ELSE '"+ACTIVE+"' END)":"CASE WHEN NVL(is_deleted,0)=1 THEN '"+INACTIVE+"' ELSE '"+ACTIVE+"' END";}
 private String normalizeStatus(String s,int d){return d==1?INACTIVE:(INACTIVE.equals(s)?INACTIVE:ACTIVE);}
 private int flag(String s){return INACTIVE.equals(s)?1:0;}
 private void updateStats(int t,int a,int i){lblTotal.setText(""+t);lblActive.setText(""+a);lblInactive.setText(""+i);}
 private String safe(String s){return s==null?"":s.trim();}
 private JLabel label(String s){JLabel l=new JLabel(s);l.setFont(new Font("Segoe UI",Font.BOLD,13));l.setForeground(muted);return l;}
 private JTextField field(String p){JTextField f=new JTextField();f.setFont(new Font("Segoe UI",0,14));f.putClientProperty("JTextField.placeholderText",p);f.setPreferredSize(new Dimension(0,42));f.setBorder(BorderFactory.createCompoundBorder(new LineBorder(line),new EmptyBorder(6,12,6,12)));return f;}
 private JButton button(String s,Color b,Color f){JButton x=new JButton(s);x.setFont(new Font("Segoe UI",1,13));x.setBackground(b);x.setForeground(f);x.setFocusPainted(false);x.setCursor(new Cursor(Cursor.HAND_CURSOR));return x;}
 private JPanel card(){JPanel p=new JPanel();p.setBackground(Color.WHITE);p.setBorder(BorderFactory.createCompoundBorder(new LineBorder(line),new EmptyBorder(20,20,20,20)));return p;}
}
