-- =========================================================
-- 20260525_audit_log_store_scope.sql
-- Bổ sung chi nhánh/module cho AUDIT_LOG
-- =========================================================

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_LOG ADD (STORE_ID VARCHAR2(30))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_LOG ADD (STORE_NAME NVARCHAR2(150))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AUDIT_LOG ADD (MODULE_NAME NVARCHAR2(100))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- Backfill store_id từ account -> employee nếu dữ liệu cũ chưa có chi nhánh
UPDATE AUDIT_LOG a
SET a.STORE_ID = (
    SELECT e.STORE_ID
    FROM ACCOUNTS ac
    JOIN EMPLOYEES e
        ON e.EMPLOYEE_ID = ac.USER_ID
    WHERE ac.ACCOUNT_ID = a.ACCOUNT_ID
      AND e.STORE_ID IS NOT NULL
      AND ROWNUM = 1
)
WHERE a.STORE_ID IS NULL
  AND EXISTS (
      SELECT 1
      FROM ACCOUNTS ac
      JOIN EMPLOYEES e
          ON e.EMPLOYEE_ID = ac.USER_ID
      WHERE ac.ACCOUNT_ID = a.ACCOUNT_ID
        AND e.STORE_ID IS NOT NULL
  );

UPDATE AUDIT_LOG
SET STORE_ID = 'CENTRAL'
WHERE STORE_ID IS NULL;

UPDATE AUDIT_LOG
SET STORE_NAME = CASE
    WHEN STORE_ID = 'CENTRAL' THEN N'Trung tâm'
    ELSE STORE_ID
END
WHERE STORE_NAME IS NULL;

UPDATE AUDIT_LOG
SET MODULE_NAME = CASE
    WHEN UPPER(ENTITY_TYPE) LIKE '%ACCOUNT%'
      OR UPPER(ENTITY_TYPE) LIKE '%ROLE%'
      OR UPPER(ENTITY_TYPE) LIKE '%USER%' THEN N'Tài khoản & phân quyền'

    WHEN UPPER(ENTITY_TYPE) LIKE '%EMPLOYEE%'
      OR UPPER(ENTITY_TYPE) LIKE '%SHIFT%' THEN N'Nhân viên & phân ca'

    WHEN UPPER(ENTITY_TYPE) LIKE '%PRODUCT%'
      OR UPPER(ENTITY_TYPE) LIKE '%INVENTORY%'
      OR UPPER(ENTITY_TYPE) LIKE '%PURCHASE%'
      OR UPPER(ENTITY_TYPE) LIKE '%SUPPLIER%' THEN N'Kho hàng'

    WHEN UPPER(ENTITY_TYPE) LIKE '%ORDER%'
      OR UPPER(ENTITY_TYPE) LIKE '%INVOICE%'
      OR UPPER(ENTITY_TYPE) LIKE '%SALE%' THEN N'Bán hàng'

    WHEN UPPER(ENTITY_TYPE) LIKE '%CUSTOMER%' THEN N'Khách hàng'
    WHEN UPPER(ENTITY_TYPE) LIKE '%PROMOTION%' THEN N'Khuyến mãi'
    WHEN UPPER(ENTITY_TYPE) LIKE '%STORE%' THEN N'Chi nhánh'
    ELSE N'Hệ thống'
END
WHERE MODULE_NAME IS NULL;

COMMIT;

SELECT STORE_ID, STORE_NAME, MODULE_NAME, COUNT(*) AS TOTAL_LOGS
FROM AUDIT_LOG
WHERE NVL(IS_DELETED, 0) = 0
GROUP BY STORE_ID, STORE_NAME, MODULE_NAME
ORDER BY STORE_ID, MODULE_NAME;
