-- =========================================================
-- 20260525_realtime_performance_indexes.sql
-- Index tối ưu realtime/search/demo cho Smart Supermarket
-- An toàn: index đã tồn tại thì bỏ qua.
-- =========================================================

CREATE OR REPLACE PROCEDURE CREATE_INDEX_IF_NOT_EXISTS(
    p_index_name IN VARCHAR2,
    p_sql        IN VARCHAR2
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = UPPER(p_index_name);

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE p_sql;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skip index ' || p_index_name || ': ' || SQLERRM);
END;
/

BEGIN
    CREATE_INDEX_IF_NOT_EXISTS('IDX_AUDIT_LOG_CREATED_AT', 'CREATE INDEX IDX_AUDIT_LOG_CREATED_AT ON AUDIT_LOG (CREATED_AT DESC)');
    CREATE_INDEX_IF_NOT_EXISTS('IDX_AUDIT_LOG_STORE_ID', 'CREATE INDEX IDX_AUDIT_LOG_STORE_ID ON AUDIT_LOG (STORE_ID)');
    CREATE_INDEX_IF_NOT_EXISTS('IDX_AUDIT_LOG_ENTITY_ACTION', 'CREATE INDEX IDX_AUDIT_LOG_ENTITY_ACTION ON AUDIT_LOG (ENTITY_TYPE, ACTION_TYPE)');

    CREATE_INDEX_IF_NOT_EXISTS('IDX_LOGIN_HISTORY_TIME', 'CREATE INDEX IDX_LOGIN_HISTORY_TIME ON LOGIN_HISTORY (LOGIN_TIME DESC)');

    CREATE_INDEX_IF_NOT_EXISTS('IDX_ACCOUNTS_USERNAME', 'CREATE INDEX IDX_ACCOUNTS_USERNAME ON ACCOUNTS (USERNAME)');
    CREATE_INDEX_IF_NOT_EXISTS('IDX_ACCOUNTS_USER_ID', 'CREATE INDEX IDX_ACCOUNTS_USER_ID ON ACCOUNTS (USER_ID)');
    CREATE_INDEX_IF_NOT_EXISTS('IDX_ACC_SESSIONS_ACTIVE', 'CREATE INDEX IDX_ACC_SESSIONS_ACTIVE ON ACCOUNT_SESSIONS (ACCOUNT_ID, STATUS, LAST_HEARTBEAT_AT)');

    CREATE_INDEX_IF_NOT_EXISTS('IDX_PRODUCTS_PRODUCT_ID', 'CREATE INDEX IDX_PRODUCTS_PRODUCT_ID ON PRODUCTS (PRODUCT_ID)');
    CREATE_INDEX_IF_NOT_EXISTS('IDX_PRODUCTS_NAME', 'CREATE INDEX IDX_PRODUCTS_NAME ON PRODUCTS (PRODUCT_NAME)');

    CREATE_INDEX_IF_NOT_EXISTS('IDX_INVENTORY_STORE_PRODUCT', 'CREATE INDEX IDX_INVENTORY_STORE_PRODUCT ON INVENTORY (STORE_ID, PRODUCT_ID)');

    CREATE_INDEX_IF_NOT_EXISTS('IDX_ORDERS_STORE_DATE', 'CREATE INDEX IDX_ORDERS_STORE_DATE ON ORDERS (STORE_ID, CREATED_AT DESC)');
    CREATE_INDEX_IF_NOT_EXISTS('IDX_ORDER_DETAILS_ORDER_ID', 'CREATE INDEX IDX_ORDER_DETAILS_ORDER_ID ON ORDER_DETAILS (ORDER_ID)');

    CREATE_INDEX_IF_NOT_EXISTS('IDX_CUSTOMERS_PHONE', 'CREATE INDEX IDX_CUSTOMERS_PHONE ON CUSTOMERS (PHONE)');
    CREATE_INDEX_IF_NOT_EXISTS('IDX_EMPLOYEES_STORE_ID', 'CREATE INDEX IDX_EMPLOYEES_STORE_ID ON EMPLOYEES (STORE_ID)');
    CREATE_INDEX_IF_NOT_EXISTS('IDX_SHIFT_EMP_DATE', 'CREATE INDEX IDX_SHIFT_EMP_DATE ON EMPLOYEE_SHIFT_ASSIGNMENTS (EMPLOYEE_ID, WORK_DATE)');
END;
/

DROP PROCEDURE CREATE_INDEX_IF_NOT_EXISTS;

COMMIT;
